//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherStudent
    {
        public int TeacherStudentID { get; set; }
        public int TeacherID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
